### ISSUE TITLE
"Enter a list of values" error apparently due to value_from_datadict removal

### ISSUE THREAD

**Issue by chellman** [lincolnloop/django-dynamic-raw-id#103]
I'm glad to see the compatibility update, but I think something was removed that shouldn't have been.

`dynamic_raw_id.widgets.DynamicRawIDMultiIdWidget.value_from_datadict` doesn't exist anymore, and when I save a model with `dynamic_raw_id_fields = (my_field)`, values like this:

`33,22,11`

Get transformed to this:

`3,3,,2,2,,1,1`

Causing an invalid list error with "Enter a list of values." displayed.

Poking around in the code, I found that restoring the missing function above, [removed here](https://github.com/lincolnloop/django-dynamic-raw-id/commit/e5966fa2b111ff3d38b801bb1006867cfab7bb3b#diff-33cdabec48f0cefabd043b0ced6ae57b28c6a3e5bb36709695102d50f45e33baL68-L78), restores the expected behavior.

(Edit - [PR is up](https://github.com/lincolnloop/django-dynamic-raw-id/pull/104).)

**Comment by chellman** [comment]
https://github.com/lincolnloop/django-dynamic-raw-id/pull/104

**Comment by bartTC** [comment]
What Python and Django version do you use? This is pretty intensively tested so I'm wondering how that could come up now.

**Comment by bartTC** [comment]
v4.2 https://pypi.org/project/django-dynamic-raw-id/ has been released with your fix. Thank you for the report, investigation and provided fix.

While the widget itself is tested, its actually never checked that data is retained correctly after the save of the admin change form itself.

**Comment by chellman** [comment]
I'll use a little bit of German I know.  Vielen dank, Martin! I really appreciate you taking the time on this.
