### ISSUE TITLE
DynamicRawIDFilter list filter value removed after search

### ISSUE THREAD

**Issue by marlonmp** [lincolnloop/django-dynamic-raw-id#109]
Hey fellas.

I was trying this library to filter using the dynamic raw id filer and I found out some issues with this filter.

When filter, the value appears in the url parameters, and the filter is applied well in the queryset

![image](https://github.com/user-attachments/assets/83a00370-fed9-4507-babd-574a43de8560)

But the filter value changes to blank

![image](https://github.com/user-attachments/assets/e5088935-c4ed-403a-87cf-6bb030617b88)

I expected the id to appear in the input value.

And the "Clear all filters" button is missing

![image](https://github.com/user-attachments/assets/412f05ed-b8aa-40a2-8c90-72955d12cdcd)

I expected something like this

![image](https://github.com/user-attachments/assets/eaf28728-7599-45df-a077-076ca8c281ff)

Another issue is when I apply another raw id filter, the previous filter is overriten

For example, I have this filter

![image](https://github.com/user-attachments/assets/dd43ca48-d900-45e1-8394-9e94e42ec1c7)

And when I search by another filter

![image](https://github.com/user-attachments/assets/aef3eec1-0d84-4d37-9091-e57f22b4a7db)

The previous query param is overriten

![image](https://github.com/user-attachments/assets/febf1545-ce6d-47b8-98df-555d0d58e8f2)

I'm using Django 4.0.7 and django-dynamic-raw-id 4.3

Are this issues bugs? or maybe is some configuratino that I'm not setting?

I thank you in advance for your help :D

**Comment by alexei** [comment]
I can confirm the issue exists on Django==4.2.16 too

**Comment by bartTC** [comment]
This has been fixed in v4.4

**Comment by alexei** [comment]
Can confirm, thanks @bartTC
