### ISSUE TITLE
How to override js function?

### ISSUE THREAD

**Issue by Jay54520** [lincolnloop/django-dynamic-raw-id#38]
I want to override `dismissRelatedLookupPopup`, because after deleting `win.close();` in `dismissRelatedLookupPopup`, I can select multiple records without closing the pop window.

**Comment by bartTC** [comment]
@Jay54520 what do you mean with 

> because after deleting win.close(); in dismissRelatedLookupPopup

Do you manually edit the file and remove it?

**Comment by bartTC** [comment]
`dismissRelatedLookupPopup` is a JS callback provided by Django Admin, please refer the Django code tracker. https://code.djangoproject.com/
