### ISSUE TITLE
Support for Djang 2.1.*

### ISSUE THREAD

**Issue by chrisspen** [lincolnloop/django-dynamic-raw-id#54]
With Django 2.1.5, this package throws a very hard to track down error:

    render() got an unexpected keyword argument 'renderer'

The traceback only lists core Django files, leaving you with virtually no way to know who the real culprit is. Through trial and error, I finally tracked down the problem to this django-salmonella. You need to add a `renderer=None` to all your widget's render() methods.

**Comment by chrisspen** [comment]
Nevermind. I just saw the name change and fixes in the new version.

You may want to update README for django-salmonella so it's clear [on the old PyPI page](https://pypi.org/project/django-salmonella/) that that specific release is essentially dead and obsolete. I've been using that version for a while and had no idea you'd changed the project.

**Comment by bartTC** [comment]
This is a great idea, thanks. https://pypi.org/project/django-salmonella/
