### ISSUE TITLE
Label of selected item is not shown when 'change' model permission is removed.

### ISSUE THREAD

**Issue by rodrigopineda028** [lincolnloop/django-dynamic-raw-id#60]
I noticed that the label of selected item isn't drawn when removing the 'change' permission from the model utilizing dynamic_raw_id. I encountered the validation made in views.py line 41 is causing this behavior 

```
if not request.user.has_perm('%s.change_%s' % (app_name, model_name)):
        return HttpResponseForbidden() 
```

shouldn't it validate the 'view' permission instead of 'change'?

thanks in advance for the help.

**Comment by bartTC** [comment]
Yes... and no. The view permission is fairly recent, it was added in Django 2.1[1]. Before that the `change` permission did make most sense, especially since this is a field you edit. 

Django 1.11 and 2.0 are still supported so it's not an option to simply replace it. 

But I don't see a problem to show the label shown if the view permission exists. And if it does not exist, then don't show it, aka thats whats the default is now anyway. 

[1] https://docs.djangoproject.com/en/dev/ref/models/options/#django.db.models.Options.default_permissions

**Comment by rodrigopineda028** [comment]
Thank you for your reply,

The view permission does exists in my model. The one I removed was the 'change' permisssion because I dont want the user to be able to edit the model nor to have acces to `mymodel/id/change` url. 
View permission is enough for selecting the raw_id_field and I agree with the default behavior you describe, label should be shown with view permission. But this default doesn't work when 'change' permission is removed.

I see the problem about version compatibility, I didn't know it was relatively new.

Just a final question, can this behavior be treated by verifying Django's version before checking if the model has 'change' permission, and to check 'view' permission accordingly to Django's newer versions (2.1 or greater). I see that version verification is made in other files within this project.

Example:

```
    if VERSION[0] >= 2 and VERSION[1] >= 1:
        if not request.user.has_perm('%s.view_%s' % (app_name, model_name)):
            return HttpResponseForbidden()
    else:
        if not request.user.has_perm('%s.change_%s' % (app_name, model_name)):
            return HttpResponseForbidden()
```

Thanks in advance for your great help.

**Comment by bartTC** [comment]
> Just a final question, can this behavior be treated by verifying Django's version before checking if the model has 'change' permission, and to check 'view' permission accordingly to Django's newer versions (2.1 or greater). I see that version verification is made in other files within this project.

Yes

**Comment by bartTC** [comment]
This is live in v2.7. thank you.
