### ISSUE TITLE
DynamicRawIDFilter is incompatible with string Primary Keys

### ISSUE THREAD

**Issue by sushifan** [lincolnloop/django-dynamic-raw-id#67]
I have a non-integer PK on my model:

```
class RelatedModel(models.Model):
    id = models.CharField(max_length=12, primary_key=True)

class MyModel(models.Model):
    related_object = models.ForeignKey('myapp.RelatedModel')
```

Adding a list filter like this correctly displays a FK filter on the admin page:

```
@admin.register(MyModel)
class MyModelAdmin(admin.ModelAdmin):
    list_filter = (('related_object_id', DynamicRawIDFilter),)
```

However, once I select any related_object and "Search", I always get this error:

"Enter a whole number."

I think DynamicRawIDFilter is currently only compatible with integer PKs.  Are you able to make it compatible with string PKs as well?  Thank you in advance.

**Comment by bartTC** [comment]
This has been working since a while. Custom Integer, String and UUID primary key fields are tested.
