### ISSUE TITLE
Having both raw_id_fields and dynamic_raw_id_fields in the ModelAdmin breaks the add link

### ISSUE THREAD

**Issue by nicolaslara** [lincolnloop/django-dynamic-raw-id#69]
Not a high priority issue, but this could be managed automatically or mentioned in the documentation.

**Comment by bartTC** [comment]
This is working, or has been working since a while. Its tested here https://github.com/lincolnloop/django-dynamic-raw-id/blob/main/dynamic_raw_id/tests/testapp/admin.py#L9-L11
