### ISSUE TITLE
Django 2.2 compatibility 

### ISSUE THREAD

**Issue by jphilip** [lincolnloop/django-dynamic-raw-id#73]
Hi there and thank you for providing this app.
It seems that after an update to Django 2.2.3, the content of the dynamic_raw_id template is not displayed anymore (neither the default or custom template). Thanks.

**Comment by jphilip** [comment]
OK, I was able to fix the issue by moving the dynamic_raw_id urls before my catch all admin urls in my project's urls.py. Somehow it worked before with django 2.1, but not 2.2.

**Comment by pb-dod** [comment]
This is related to this change from django 3.2:
>The admin now installs a final catch-all view that redirects unauthenticated users to the login page, regardless of whether the URL is otherwise valid. This protects against a potential model enumeration privacy issue.

**Comment by bartTC** [comment]
Fixed with Version 3.0
