### ISSUE TITLE
Edit option not working with dynamic_raw_id_field

### ISSUE THREAD

**Issue by yagss** [lincolnloop/django-dynamic-raw-id#76]
Hi, I had to implement this lib to display customer information in a raw_id_field field and everything is working fine (see image below), however the edit option always appears disabled, how can I make it work with this?

![image](https://user-images.githubusercontent.com/13019314/124881787-5d196a80-df95-11eb-9c98-5daa25350c1b.png)

thanks in advance

**Comment by yagss** [comment]
Well, I figured out how to make it works just adding a few lines into dynamic_raw_id.js file

**Comment by joejoe-am** [comment]
@yagss  hey that would help if explain more that me and others can wont open new issue. thank you

**Comment by joejoe-am** [comment]
well i fixed that by changing the sort of urls which starts with admin/
