### ISSUE TITLE
Multiselect record in the popup for many to many

### ISSUE THREAD

**Issue by madthew** [lincolnloop/django-dynamic-raw-id#84]
Hi, I am not sure if I am doing something wrong but I would expect a checkbox in the dynamic_raw_id_many to multiselect records?

**Comment by bartTC** [comment]
@madthew mmh, not quite sure what you mean. Would you provide a screenshot of that area?

**Comment by madthew** [comment]
What I mean is that when I click on the lens that open the foreign key selection within the dynamic_raw_id_many  example, I would expect to see checkboxes, and not having to click everytime, then click again on the lens, pick an additional one, etc.

**Comment by bartTC** [comment]
I see what you mean. Strictly said this is a Django Admin issue, not one of this widget. It just sits on top of the regular field that works as you described, and adds the labels to the right. Right now it would be excessive to refactor and rewrite all of this.
