### ISSUE TITLE
Breaks with Django 4.2 due to changes for multiple popups

### ISSUE THREAD

**Issue by CelestialGuru** [lincolnloop/django-dynamic-raw-id#94]
## Bug

1. Click spyglass
2. Child window opens
3. You make your select by clicking on the object
4. Nothing happens. Console logs show an `Uncaught TypeError: elem is null` at `/static/dynamic_raw_id/js/dynamic_raw_id.js:19`.

## Expected

1. Click spyglass
2. Child window opens
3. You make your selection by clicking on the object
4. The window closes
5. The id is added to the list and the name is shown too

## Cause

In 4.2a1, Django [added support for multiple popups](https://github.com/django/django/commit/492ed60f236d770eb9a6d56d85ff2550bb1ecfff). Child windows are now created with different names than they did before.

```javascript
// RelatedObjectLookups.js
function showAdminPopup(triggeringLink, name_regexp, add_popup) {
    const name = addPopupIndex(triggeringLink.id.replace(name_regexp, '')); // appends `__{popupIndex}` to name
    ...
    const win = window.open(href, name, 'height=500,width=800,resizable=yes,scrollbars=yes'); // window.name has `__{popupIndex}` at the end
    ...
}
```

Their `dismissRelatedLookupPopup` handles the new window name format:

```javascript
// django RelatedObjectLookups.js
function dismissRelatedLookupPopup(win, chosenId) {
    const name = removePopupIndex(win.name); // removes `__{n}` from name
    const elem = document.getElementById(name);]
    if (elem.classList.contains('vManyToManyRawIdAdminField') && elem.value) {
        elem.value += ',' + chosenId;
    } else {
        document.getElementById(name).value = chosenId;
    }
    const index = relatedWindows.indexOf(win);
    if (index > -1) {
        relatedWindows.splice(index, 1);
    }
    win.close();
}
```

The problem is in this libraries code, it's not expecting `__{n}` and so doesn't remove it:
```javascript
// django-dynamic-raw-id RelatedObjectLookups.js
function dismissRelatedLookupPopup(win, chosenId) {
    const name = windowname_to_id(win.name); // fails to remove `__{n}`
    const elem = document.getElementById(name); // fails to get element
    if (elem.className.indexOf('vManyToManyRawIdAdminField') !== -1 && elem.value) { // Uncaught TypeError: elem is null
        elem.value += `,${chosenId}`;
    } else {
        elem.value = chosenId;
    }
    django.jQuery(elem).trigger('change');
    win.close();
}
```

**Comment by CelestialGuru** [comment]
It seems the latest version of Django that works this package works with is 4.0.8

**Comment by gauravgupta369** [comment]
Is there any way to use it with Django 4.2?

**Comment by nathanielwarner** [comment]
For anyone finding this, I created a branch with a minimal change that fixes it: https://github.com/nathanielwarner/django-dynamic-raw-id/tree/fix-django-4.2

**Comment by bartTC** [comment]
Would you make a PR with these code changes?

**Comment by bartTC** [comment]
Thank you! I have added it to #98 and hope to release it later today.

**Comment by bartTC** [comment]
This is fixed in https://pypi.org/project/django-dynamic-raw-id/4.0/
